#!/usr/bin/env bash

set -e

current_branch=$(git branch --show-current)

trap 'echo "Installation failed!"; git checkout $current_branch' ERR

branches=$(git branch -r | grep -v 'HEAD\|main\|master' | sed 's|^[[:space:]]*origin/||')

selected_branch=$(echo "$branches" | gum choose --header="Which computer configuration do you want to install?")

if [[ -n "$selected_branch" ]]; then
    echo "Installing $selected_branch configurations"
    git checkout $selected_branch
    ./install
    echo "Finish $selected_branch installation"
    git checkout $current_branch
fi